import {
  Image,
  FileImage,
  Scissors,
  RefreshCw,
  Type,
  Ruler,
  FileText,
  LayoutGrid,
  Hash,
  BookOpen,
  FileType,
  QrCode,
  Barcode,
  Tag,
  Regex,
  Palette,
  Pipette,
  Rainbow,
  PenLine,
  Crop,
  Square,
  GalleryVertical,
  Stamp,
  Sparkles,
  Contrast,
  Eye,
  Eraser,
  Library,
  Blend,
  Calculator,
  LineChart,
  Variable,
  Binary,
  Clock,
  Scale,
  FileCode,
  ScanLine,
  Slice,
  FileSearch,
  Languages,
  Layers,
  Home,
  Shield,
  Star,
  Command,
  LucideIcon
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  image: Image,
  fileImage: FileImage,
  scissors: Scissors,
  refreshCw: RefreshCw,
  type: Type,
  ruler: Ruler,
  fileText: FileText,
  layoutGrid: LayoutGrid,
  hash: Hash,
  bookOpen: BookOpen,
  fileType: FileType,
  qrCode: QrCode,
  barcode: Barcode,
  tag: Tag,
  regex: Regex,
  palette: Palette,
  pipette: Pipette,
  rainbow: Rainbow,
  penLine: PenLine,
  crop: Crop,
  square: Square,
  galleryVertical: GalleryVertical,
  stamp: Stamp,
  sparkles: Sparkles,
  contrast: Contrast,
  eye: Eye,
  eraser: Eraser,
  library: Library,
  blend: Blend,
  calculator: Calculator,
  lineChart: LineChart,
  variable: Variable,
  binary: Binary,
  clock: Clock,
  scale: Scale,
  fileCode: FileCode,
  scanLine: ScanLine,
  slice: Slice,
  fileSearch: FileSearch,
  languages: Languages,
  layers: Layers,
  home: Home,
  shield: Shield,
  star: Star,
  command: Command,
};

export type IconName = keyof typeof iconMap;
